package org.aadi.mongoDB;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class BootMongoDbAutoGeneratedIdDemoApplicationTests {

	@Test
	void contextLoads() {
	}

}
